name: environment test
permissions:
  contents: read
on:
  push:
    branches:
      main
  workflow_dispatch:
jobs:
  envtest:
   
    name: environ
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: print env
        run: |
          env|sed "/token/d;/Token/d;/TOKEN/d" > /tmp/env
          echo lscpu: >> /tmp/env
          lscpu >> /tmp/env
          echo kvm: >> /tmp/env
          ls /dev/kvm 2>> /tmp/env >> /tmp/env
          echo lspci: >> /tmp/env
          lspci -kn >> /tmp/env
          echo id: >> /tmp/env
          id >> /tmp/env
          echo sudo : >> /tmp/env
          sudo -l >> /tmp/env
          echo df: >> /tmp/env
          df -h >> /tmp/env
          echo packages: >> /tmp/env
          sudo dpkg -l >> /tmp/env
          echo lsblk: >> /tmp/env
          lsblk >> /tmp/env


      
      - name: upload env
        uses: actions/upload-artifact@v5
        with:
          name: env
          path: |
            /tmp/env
